apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ingress-nginx
  project: infra
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.10.0
    helm:
      releaseName: ingress-nginx
      values: |-
        controller:
          image:
            allowPrivilegeEscalation: false
          ingressClass: nginx
          ingressClassResource:
            name: nginx
          containerSecurityContext:
            capabilities:
              add:
                - NET_BIND_SERVICE
              drop:
                - ALL
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
          networkPolicy:
            enabled: true
          service:
            annotations:
              metallb.universe.tf/address-pool: static
            loadBalancerIP: "192.168.7.101"
          defaultBackend:
            networkPolicy:
              enabled: true
          


