apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  project: infra
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.5.2
    helm:
      releaseName: ingress-nginx
      values: |-
        controller:
          service:
            annotations:
              metallb.universe.tf/address-pool: static
            loadBalancerIP: "192.168.7.101"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: nginx
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
